export const QK = {
  me: ['auth', 'me'] as const,
  exchangeRate: ['currency', 'rate'] as const,
  dashboard: ['dashboard', 'summary'] as const,
  cashPosition: ['dashboard', 'cash-position'] as const,
  inventoryProducts: ['inventory', 'products'] as const,
  inventory: (filters?: object) => ['inventory', filters] as const,
  salesHistory: (filters?: object) => ['sales', 'history', filters] as const,
  topProducts: (filters?: object) => ['sales', 'top-products', filters] as const,
  suppliers: ['dashboard', 'suppliers'] as const,
  supplierDetail: (id: string) => ['dashboard', 'suppliers', id] as const,
  debtors: ['dashboard', 'debtors'] as const,
  debtorDetail: (id: string) => ['dashboard', 'debtors', id] as const,
  profitByProduct: (filters?: object) => ['dashboard', 'profit-by-product', filters] as const,
  profitBySource: ['dashboard', 'profit-by-source'] as const,
  alerts: ['dashboard', 'alerts'] as const,
  consignmentsIncoming: ['consignments', 'incoming'] as const,
  consignmentsOutgoing: ['consignments', 'outgoing'] as const,
  pendingPayments: ['payments', 'pending-from-debtors'] as const,
  externalContacts: ['external-contacts'] as const,
  externalContactDetail: (id: string) => ['external-contacts', id] as const,
  externalContactTransactions: (id: string, page?: number, limit?: number) =>
    ['external-contacts', id, 'transactions', page ?? 1, limit ?? 20] as const,
  expenses: (filters?: object) => ['expenses', filters] as const,
  withdrawals: ['withdrawals'] as const,
  withdrawalAvailable: ['withdrawals', 'available'] as const,
  stockMovements: (filters?: object) => ['inventory', 'movements', filters] as const,
  stockMovementsByEntry: (entryId: string) =>
    ['inventory', 'entries', entryId, 'movements'] as const,
  employments: (filters?: object) => ['employments', filters] as const,
  employmentDetail: (id: string) => ['employments', id] as const,
  salaryPayments: (filters?: object) => ['salary-payments', filters] as const,
  salaryPaymentsPending: ['salary-payments', 'pending'] as const,
  salarySummary: (employmentId: string, periodMonth?: string) =>
    ['salary-payments', 'summary', employmentId, periodMonth ?? 'current'] as const,
  pricing: ['pricing'] as const,
  activityLogs: (filters?: object) => ['activity-logs', filters] as const,
} as const;
