export const QK = {
  me: ['auth', 'me'] as const,
  exchangeRate: ['currency', 'rate'] as const,
  dashboard: ['dashboard', 'summary'] as const,
  inventoryProducts: ['inventory', 'products'] as const,
  inventory: (filters?: object) => ['inventory', filters] as const,
  salesHistory: (filters?: object) => ['sales', 'history', filters] as const,
  topProducts: (filters?: object) => ['sales', 'top-products', filters] as const,
  suppliers: ['dashboard', 'suppliers'] as const,
  supplierDetail: (id: string) => ['dashboard', 'suppliers', id] as const,
  debtors: ['dashboard', 'debtors'] as const,
  debtorDetail: (id: string) => ['dashboard', 'debtors', id] as const,
  profitByProduct: (filters?: object) => ['dashboard', 'profit-by-product', filters] as const,
  profitBySource: ['dashboard', 'profit-by-source'] as const,
  alerts: ['dashboard', 'alerts'] as const,
  consignmentsIncoming: ['consignments', 'incoming'] as const,
  consignmentsOutgoing: ['consignments', 'outgoing'] as const,
  pendingPayments: ['payments', 'pending-from-debtors'] as const,
  externalContacts: ['external-contacts'] as const,
  externalContactDetail: (id: string) => ['external-contacts', id] as const,
  stockMovements: (filters?: object) => ['inventory', 'movements', filters] as const,
  stockMovementsByEntry: (entryId: string) =>
    ['inventory', 'entries', entryId, 'movements'] as const,
} as const;
