export const QK = {
  me: ['auth', 'me'] as const,
  inventory: (filters?: object) => ['inventory', filters] as const,
  salesHistory: (filters?: object) => ['sales', 'history', filters] as const,
  topProducts: (filters?: object) => ['sales', 'top-products', filters] as const,
  dashboard: ['dashboard', 'summary'] as const,
  suppliers: ['dashboard', 'suppliers'] as const,
  supplierDetail: (id: string) => ['dashboard', 'suppliers', id] as const,
  debtors: ['dashboard', 'debtors'] as const,
  debtorDetail: (id: string) => ['dashboard', 'debtors', id] as const,
  profitByProduct: ['dashboard', 'profit-by-product'] as const,
  alerts: ['dashboard', 'alerts'] as const,
  userSearch: (q: string) => ['users', 'search', q] as const,
  consignmentsIncoming: ['consignments', 'incoming'] as const,
  consignmentsOutgoing: ['consignments', 'outgoing'] as const,
  exchangeRate: ['currency', 'rate'] as const,
  externalContacts: ['external-contacts'] as const,
  externalContactDetail: (id: string) => ['external-contacts', id] as const,
} as const;
