export const QK = {
  me: ['auth', 'me'] as const,
  inventoryProducts: ['inventory', 'products'] as const,
  inventory: (filters?: object) => ['inventory', filters] as const,
  salesHistory: (filters?: object) => ['sales', 'history', filters] as const,
  topProducts: (filters?: object) => ['sales', 'top-products', filters] as const,
  dashboard: ['dashboard', 'summary'] as const,
  suppliers: ['dashboard', 'suppliers'] as const,
  supplierDetail: (id: string) => ['dashboard', 'suppliers', id] as const,
  profitByProduct: ['dashboard', 'profit-by-product'] as const,
  alerts: ['dashboard', 'alerts'] as const,
  userSearch: (q: string) => ['users', 'search', q] as const,
  exchangeRate: ['currency', 'rate'] as const,
  salaryPaymentsPending: ['salary-payments', 'pending'] as const,
  salaryHistory: ['salary-payments', 'history'] as const,
  salarySummary: (employmentId: string, periodMonth: string) =>
    ['salary-payments', 'summary', employmentId, periodMonth] as const,
  expenses: (params?: object) => ['expenses', params ?? {}] as const,
  cashPosition: ['dashboard', 'cash-position'] as const,
} as const;
